config/routes.rb
Rails.application.routes.draw do
  get "profile/index"

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  resources :genres
  resources :authors
  resources :books
  resources :purchases
  resources :reviews

  root "books#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
    validates :author, presence: true

    ## To delete duplicate records
    # Author.where.not(id: Author.group(:author).select("min(id)")).destroy_all

    def self.already_has_author(author_param)
        Author.pluck(:author).include?(author_param)
    end

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  belongs_to :user

  has_many :reviews

  validates :name, presence: true
  validates :author_id, presence: true
  validates :genre_id, presence: true 
  validates :published_date, presence: true
  validates :description, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books

    validates :name, presence: true

    ## To delete duplicate records
    # Genre.where.not(id: Genre.group(:name).select("min(id)")).destroy_all

    def self.already_has_genre(genre_param)
        Genre.pluck(:name).include?(genre_param)
    end

end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :review, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :purchases
  has_many :reviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def index
        @authors = Author.all
    end

    def show
        @author = Author.find(params[:id])
        @books = @author.books.all
    end

    def new
        session[:return_to] ||= request.referer
        @author = Author.new
        @error = false
        if params[:author_exists]
            @error = true
        end
    end

    def create
        if Author.already_has_author(author_params[:author])
            redirect_to new_author_url(author_exists: true)
        else
            @author = Author.create(author_params)
            if @author.save
                redirect_to session.delete(:return_to)
            else
                render 'new'
            end
        end
    end

    def edit
        @author = Author.find(params[:id])
        @error = false
        if params[:author_exists]
            @error = true
        end
    end

    def update
        if Author.already_has_author(author_params[:author])
            redirect_to edit_author_url(author_exists: true)        
        else
            @author = Author.find(params[:id])
            if @author.update(author_params)
                redirect_to '/authors'
            else
                render 'edit'
            end
        end
    end

    private
    def author_params
        params.require(:author).permit(:author)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
    end

    def show
        @book = Book.find(params[:id])
    end

    def new
        @book = Book.new
    end

    def create
        @book = current_user.books.create(book_params)
        if @book.save
            redirect_to '/profile/index'
        else
            render 'new'
        end
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            redirect_to '/profile/index'
        else
            render 'edit'
        end
    end

    private
    def book_params
        params.require(:book).permit(:name,:author_id,:genre_id,:description,:published_date)
    end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
    def index
        @genres = Genre.all
    end

    def show
        @genre = Genre.find(params[:id])
        @books = @genre.books.all
    end

    def new
        @genre = Genre.new
        @error = false
        if params[:genre_exists]
            @error = true
        end
    end

    def create
        if Genre.already_has_genre(genre_params[:name])
            redirect_to new_genre_url(genre_exists: true)
        else
            @genre = Genre.create(genre_params)
            if @genre.save
                redirect_to '/books/new'
            else
                render 'new'
            end
        end
    end

    def edit
        @genre = Genre.find(params[:id])
        @error = false
        if params[:genre_exists]
            @error = true
        end
    end

    def update
        if Genre.already_has_genre(genre_params[:name])
            redirect_to edit_genre_url(genre_exists: true)
        else
            @genre = Genre.find(params[:id])
            if @genre.update(genre_params)
                redirect_to '/genres'
            else
                render 'new'
            end
        end
    end

    private
    def genre_params
        params.require(:genre).permit(:name)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :check_user

  def index
  end

  private
  def check_user
    if !current_user
      redirect_to new_user_session_path
    end
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
    def new
        @purchase = current_user.purchases.new
    end

    def create
        @purchase = current_user.purchases.create(purchase_params)
        @purchase.save
        redirect_to '/profile/index'
    end

    private
    def purchase_params
        params.require(:purchase).permit(:book_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @book = Book.find(params[:book_id])
        @review = @book.reviews.new
    end

    def create
        @book = Book.find(params[:review][:book_id])
        @review = @book.reviews.create(review_params)
        if @review.save
            redirect_to book_path(@book)
        else
            render 'new'
        end
    end

    def edit
        @book = Book.find(params[:book_id])
        @review = @book.reviews.find(params[:id])
    end

    def update
        @book = Book.find(params[:review][:book_id])
        @review = @book.reviews.find(params[:id])
        if @review.update(review_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end

    private
    def review_params
        params.require(:review).permit(:user_id,:review,:book_id)
    end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/authors/_form.html.slim
= form_with(model: @author, local: true) do |form|
    - if @error
        p That author already exists in the database
    .field
        = form.label :author
        = form.text_field :author
    .actions
        = form.submit

    p = link_to 'Back', :back

app/views/authors/_list_of_authors.html.slim
h1 List of Authors in database
table
    - @authors.order(:author).each do |author|
        tr
            td = link_to author.author, author_path(author)
            - if current_user
                td = link_to 'Edit', edit_author_path(author)

app/views/authors/_list_of_books.html.slim
table
    tr
        th
            strong Title
        th
            strong Genre
    - @books.each do |book|
        tr
            td = link_to book.name, book_path(book)
            td = link_to book.genre.name, genre_path(book.genre)

app/views/authors/edit.html.slim
h1 Edit this Author's details
= render 'form'

app/views/authors/index.html.slim
= render 'list_of_authors'

app/views/authors/new.html.slim
h1 Add a new author to the database

= render 'form'

app/views/authors/show.html.slim
h1 = "Books by #{@author.author}"

= render 'list_of_books'

app/views/books/_book_details.html.slim
table
    tr
        td
            strong Title:
        td #{@book.name}
    tr
        td
            strong Author:
        td #{@book.author.author}
    tr
        td
            strong Genre:
        td #{@book.genre.name}
    tr
        td
            strong Published:
        td #{@book.published_date.to_date}
    tr
        td
            strong Added by:
        td #{@book.user.email}
    tr
        td
            strong Description:
        td #{@book.description}

- if current_user
    = button_to 'PURCHASE', purchases_path('purchase': {'book_id': @book}), method: :post

app/views/books/_form.html.slim
= form_with(model: @book, local: true) do |form|
    .field
        = form.label :name, 'Title of Book'
        = form.text_field :name
    .field
        = form.label :author_id
        = form.collection_select :author_id, Author.all.order(:author), :id, :author, include_blank: true
        = link_to '(New)', new_author_path
    .field
        = form.label :genre_id
        = form.collection_select :genre_id, Genre.all.order(:name), :id, :name, include_blank: true
        = link_to '(New)', new_genre_path
    .field
        = form.label :description
        = form.text_area :description
    .field
        = form.label :published_date
        = form.date_field :published_date
    .actions
        = form.submit
    p = link_to 'Back', :back

app/views/books/_list_of_books.html.slim
h3 List of available books
table
    tr
        th
            strong Title
        th
            strong Author
        th
            strong Genre

    - @books.order(:name).each do |book|
        - if book.user != current_user
            tr
                td
                    = link_to book.name, book_path(book)
                td
                    = link_to book.author.author, author_path(book.author)
                td
                    = link_to book.genre.name, genre_path(book.genre)

app/views/books/edit.html.slim
h1 = "Edit book details"
= render 'form'

app/views/books/index.html.slim
- if current_user
    p = "Welcome #{current_user.first_name} #{current_user.last_name}!"

h1 Welcome to the bookstore!

= render 'list_of_books'

app/views/books/new.html.slim
h1 Add a new book to the database

= render 'form'

app/views/books/show.html.slim
= render 'book_details'

= render '/reviews/list_of_reviews'

app/views/genres/_form.html.slim
= form_with(model: @genre, local: true) do |form|
    - if @error
        p That genre already exists in the database
    .field
        = form.label :name
        = form.text_field :name
    .actions
        = form.submit

    p = link_to 'Back', :back        

app/views/genres/_list_of_books.html.slim
table
    tr
        th
            strong Title
        th
            strong Author
    - @books.each do |book|
        tr
            td = link_to book.name, book_path(book)
            td = link_to book.author.author, author_path(book.author)

app/views/genres/_list_of_genres.html.slim
h1 List of Genres in database
table
    - @genres.order(:name).each do |genre|
        tr
            td = link_to genre.name, genre_path(genre)
            - if current_user
                td = link_to 'Edit', edit_genre_path(genre)

app/views/genres/edit.html.slim
h1 Edit this Genre's details

= render 'form'

app/views/genres/index.html.slim
= render 'list_of_genres'

app/views/genres/new.html.slim
h1 Add a new genre to the database

= render 'form'

app/views/genres/show.html.slim
h1 = "Books listed under #{@genre.name}"

= render 'list_of_books'